spring:
  application.name: metrics-manager
  task.scheduling.pool.size: 2

server:
  port: ${PORT:8080}

hikari:
  jdbc-url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
  schema: ${DB_SCHEMA:public}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver
